[package]
name = "advent6_customs"
version = "0.1.0"
authors = ["Tom Bailey <thomas.bailey0@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
